name: Question ❓
description: Usage question or discussion about Carbon AI chat components.
title: '[Question]: '
labels: ['type: question ❓', 'status: needs triage 🕵️‍♀️']
body:
  - type: markdown
    attributes:
      value: '## Hi there! 👋'
  - type: markdown
    attributes:
      value:
        Hope everything is going okay using projects from the Carbon AI Chat. It looks like you might have a question about our work, so we
        wanted to share a couple of resources that you could use if you haven't tried them yet 🙂
  - type: markdown
    attributes:
      value:
        If you're an IBMer, we have a Slack channel, `#carbon-ai-chat`, available across
        all IBM Workspaces.
  - type: textarea
    id: summary
    attributes:
      label: Question for Carbon AI chat
      description: 'Let us know how we can help!'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/carbon-design-system/carbon/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
